### PR TITLE
Also search nested folders under PublicAssemblies

### PR DESCRIPTION
**Pull request by emrekultursay**
This fixes issue #38

### CODE REVIEW

**Comment by josetr** [comment]
Thanks a lot for the contribution. I think we may have an issue with the versions tho since there can be multiple ones installed at the same time, and your solution would pick one randomly.

These are some of the folders that I have on my VS installation:

```
StreamJsonRpc.1.x
StreamJsonRpc.2.x
MessagePack.2.x
Nerdbank.Streams.2.x
Newtonsoft.Json.9.0.0.1
Newtonsoft.Json.12.0.0.2
Newtonsoft.Json.13.0.1.0
Newtonsoft.Json.13.0.3.0
```

I'm suggesting an alternative solution:

```.cs

if (searchNestedDirs)
{
    List<Assembly> assemblyFiles = new ();

    foreach (string dir in Directory.GetDirectories(probingPath, $"{assemblyName.Name}.*"))
    {
        assemblyFile = Path.Combine(dir, $"{assemblyName.Name}.dll");

        if (File.Exists(assemblyFile))
        {
            var assembly = Assembly.LoadFrom(assemblyFile);
            if (assembly != null)
                assemblyFiles.Add(assembly);
        }
    }

    if (assemblyFiles.Count > 0)
    {
        var bestMatch =

        assemblyFiles.FirstOrDefault(x =>
            x.GetName().Version.Major == assemblyName.Version.Major &&
            x.GetName().Version.Minor == assemblyName.Version.Minor &&
            x.GetName().Version.Revision == assemblyName.Version.Revision) ??

        assemblyFiles.FirstOrDefault(x =>
            x.GetName().Version.Major == assemblyName.Version.Major &&
            x.GetName().Version.Minor == assemblyName.Version.Minor) ??

        assemblyFiles.FirstOrDefault(x =>
            x.GetName().Version.Major == assemblyName.Version.Major);

        if (bestMatch != null)
            return bestMatch;

        return assemblyFiles.OrderBy(x => x.GetName().Version.Major).LastOrDefault();
    }
}
```

**Comment by emrekultursay** [comment]
You are right, thanks for the noticing it. I applied your suggestion, except I avoided loading the candidate assemblies (by calling `Assembly.LoadFrom()`)  just to get their versions. I presumed it would be slow to load them and may cause conflicts. LMK if you want me to stick to your version.

**Comment by josetr** [comment]
Thanks for improving the solution, altho it seems like you've removed the `searchPattern` from GetDirectories which I added.

Don't you think we should keep it?

The pattern that they are using seems pretty standard right now. If they come up with a new one, we can search more aggressively in the future.

**Comment by emrekultursay** [comment]
Thanks, I hadn't noticed that your suggestion had that diff. I added it. PTAL.

**Pull request merged**
